reserved = {
    'var': 'VAR',
    'if': 'IF',
    'then': 'THEN',
    'else': 'ELSE',
    'while': 'WHILE',
    'do': 'DO',
    'input': 'INPUT',
    'output': 'OUTPUT'
}

literals = {
    '{': 'LBRACKET',
    '}': 'RBRACKET',
    '(': 'LPARANTHESIS',
    ')': 'RPARANTHESIS',
    '=': 'EQUAL',
    '+': 'PLUS',
    '-': 'MINUS',
    '*': 'MULTIPLY',
    '/': 'DIVIDE',
    '%': 'MODULO',
    '<': 'LESS',
    '>': 'MORE',
    ',': 'COMMA',
    ':': 'COLON',
    ';': 'SEMICOLON',
    '**': 'EXPONENTIATION',
    '//': 'FLOOR DIVISION',
    '+=': 'INCREMENT',
    '-=': 'DECREMENT',
    '*=': 'INCREMENT_TIMES',
    '/=': 'DECREMENT_TIMES',
    '==': 'COMP_EQUAL',
    '!=': 'NOT_EQUAL',
    '>=': 'MORE-EQUAL',
    '<=': 'LESS-EQUAL',
    '&': 'AND',
    '|': 'OR',
    '!': 'NOT',
    '~': 'NOT',
    '^': 'XOR'
}